imports:
  - { resource: ./application.yaml }

services:
  Example.EnvironmentArranger:
    class: ../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Example.Shared.ConnectionManager']