services:
  Mechoui.Courses.domain.CourseRepository:
    class: ../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@Mechoui.Shared.ConnectionManager']

  Mechoui.Courses.application.CourseCreator:
    class: ../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: ['@Mechoui.Courses.domain.CourseRepository', '@Mechoui.Shared.domain.EventBus']

  Mechoui.courses.Boom:
    class: ../../../../Contexts/mechoui/Courses/application/Create/Boom
    tags:
      - { name: 'domainEventSubscriber' }

  Mechoui.courses.CreateCourseCommandHandler:
    class: ../../../../Contexts/Mooc/Courses/application/Create/CreateCourseCommandHandler
    arguments: ['@Mechoui.Courses.application.CourseCreator']
    tags:
      - { name: 'commandHandler' }
