services:
  Shared.Logger:
    class: ../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Example.Shared.MongoConfig:
    factory:
      class: ../../../../Contexts/Mooc/Shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Example.Shared.ConnectionManager:
    factory:
      class: ../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['backoffice', '@Example.Shared.MongoConfig']
  
  Example.Shared.CommandHandlers:
    class: ../../../../Contexts/Shared/infrastructure/CommandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  Example.Shared.domain.CommandBus:
    class: ../../../../Contexts/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Example.Shared.CommandHandlers']

  Example.Shared.RabbitMQConfig:
    factory:
      class: ../../../../Contexts/Mooc/Shared/infrastructure/RabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'

  Example.Shared.domain.EventBus:
    factory:
      class: ../../../../Contexts/Mooc/Shared/infrastructure/RabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@Example.Shared.DomainEventFailoverPublisher',
        '@Example.Shared.RabbitMQConnection',
        '@Example.Shared.RabbitMQqueueFormatter',
        '@Example.Shared.RabbitMQConfig'
      ]

  Example.Shared.RabbitMQQueueFormatter:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['backoffice']

  Example.Shared.RabbitMQConnection:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMqConnection
    arguments: ['@Example.Shared.RabbitMQConfig']

  Example.Shared.RabbitMQqueueFormatter:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['backoffice']

  Example.Shared.DomainEventFailoverPublisher:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/DomainEventFailoverPublisher/DomainEventFailoverPublisher
    arguments: ['@Example.Shared.ConnectionManager']
  
  Example.Shared.QueryHandlers:
    class: ../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  Example.Shared.domain.QueryBus:
    class: ../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Example.Shared.QueryHandlers']