imports:
  - { resource: ./application.yaml }

services:
  Mooc.EnvironmentArranger:
    class: ../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Mechoui3.Shared.ConnectionManager']
